export { authRouter } from './authRouter'
export { resourcesRouter } from './resourcesRouter'
export { topicsRouter } from './topicsRouter'
export { categoriesRouter } from './categoriesRouter'
export { mediaRouter } from './mediaRouter'
