services:
  api:
    image: back:latest
    build:
      context: ./back
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    env_file:
      - ./back/.env

  front:
    depends_on:
      - api
    build:
      context: ./front
      dockerfile: Dockerfile
    image: front:latest
    ports:
      - "80:80"
    environment:
      - API_URL=http://api:3000
