import type {
  TFavorites,
  TGetTopics,
  TTopic,
  TUserData,
  TFilters,
  TResource,
  TCategory,
  TLinkStyled,
  TCardResource,
  TTopicResource,
  TEditResourceProps,
  TMappedTopics,
  TVoteCountResponse,
  TVoteMutationData,
  TResourceTitleLink,
  TGetTypes,
  TUserVote,
  TVoteCount,
} from './types'

export type {
  TFavorites,
  TGetTopics,
  TTopic,
  TUserData,
  TFilters,
  TResource,
  TCategory,
  TLinkStyled,
  TCardResource,
  TTopicResource,
  TEditResourceProps,
  TMappedTopics,
  TVoteCountResponse,
  TVoteMutationData,
  TResourceTitleLink,
  TGetTypes,
  TUserVote,
  TVoteCount,
}
