export const urls = {
  register: '/api/v1/auth/register',
  logIn: '/api/v1/auth/login',
  logOut: '/api/v1/auth/logout',
  createResource: '/api/v1/resources',
  getMe: '/api/v1/auth/me',
  getTopics: '/api/v1/topics',
  postTopics: '/api/v1/topics',
  patchTopics: '/api/v1/topics',
  getCategories: '/api/v1/categories',
  getResources: '/api/v1/resources',
  getResourcesByUser: '/api/v1/resources/me',
  getResourcesById: '/api/v1/resources/id/',
  getTypes: '/api/v1/types',
  getFavorites: '/api/v1/resources/favorites',
  updateResource: '/api/v1/resources',
  vote: '/api/v1/vote/',
  users: '/api/v1/users',
  favorites: '/api/v1/favorites',
  postStatus: '/api/v1/seen',
}
