export const urls = {
  register: '/api/v1/auth/register',
  logIn: '/api/v1/auth/login',
  logOut: '/api/v1/auth/logout',
  createResource: '/api/v1/resources',
  getMe: '/api/v1/auth/me',
  getTopics: '/api/v1/topics',
  getCategories: '/api/v1/categories',
  getResources: '/api/v1/resources',
  getTypes: '/api/v1/types',
  getFavorites: '/api/v1/resources/favorites',
  getResourcesByUser: '/api/v1/resources/me',
  updateResource: '/api/v1/resources',
  vote: '/api/v1/vote/',
}
