export { loginController } from './auth/loginController'
export { registerController } from './auth/registerController'
export { authMeController } from './auth/authMeController'
export { createResource } from './resourceController'
export { getTopics, getTopicsByCategoryId } from './topicController'
export { getCategories } from './categoryController'