export { loginController } from './loginController'
export { registerController } from './registerController'
export * from './resourceController'
export { getTopics, getTopicsByCategoryId } from './topicController'
export { getCategories } from './categoryController'