/**
 * Generated by @openapi-codegen
 *
 * @version 0.16.0
 */
import * as reactQuery from "@tanstack/react-query";
import { useOpenapiContext, OpenapiContext } from "./openapiContext";
import type * as Fetcher from "./openapiFetcher";
import { openapiFetch } from "./openapiFetcher";

export type QueryOperation = {
  path: string;
  operationId: never;
  variables: unknown;
};
