name: build_front

on:
  push:
    branches:
      - main
    paths:
      - "front/**"

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Grab version
        id: version
        run: echo "::set-output name=version::$(jq -r '.version' front/package.json)"

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: front
          push: true
          tags: kevinmamaqi/ita-wiki-front:v${{ steps.version.outputs.version }}

      - name: Update version
        run: |
          git config --global user.name "ITA Wiki bot"
          git config --global user.email "bot@itawiki.com"
          version=$(grep version: ./config/dev/front.yml | awk '{print $2}')
          sed -i "s/version: $version/version: ${{ steps.version.outputs.version }}/" ./config/dev/front.yml
          git add ./config/dev/front.yml
          git commit -m "Bump front image to v${{ steps.version.outputs.version }}"

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          title: "Bump front image version to v${{ steps.version.outputs.version }}"
          commit-message: "Bump front image version to v${{ steps.version.outputs.version }}"
          branch: "bump-front-to-v${{ steps.version.outputs.version }}"
          delete-branch: true
          token: ${{ secrets.GITHUB_TOKEN }}
          author: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
          assignees: ${{ github.actor }}
