name: build_back

on:
  pull_request:
    branches:
      - main
    types:
      - closed
    paths:
      - "back/**"

jobs:
  build_and_deploy:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Grab version
        id: version
        run: echo "::set-output name=version::$(jq -r '.version' back/package.json)"

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: back
          push: true
          tags: kevinmamaqi/ita-wiki-back:v${{ steps.version.outputs.version }}
