name: deploy_sso_dev

on:
  pull_request:
    branches:
      - main
    types:
      - closed
    paths:
      - "config/dev/sso.yml"

jobs:
  deploy_sso_dev:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Get versions
        id: versions
        run: |
          sso_service_version=$(grep version: ./config/dev/service_sso.yml | awk '{print $2}')
          usuaris_web_version=$(grep version: ./config/dev/web_usuaris.yml | awk '{print $2}')
          echo "::set-output name=sso_service_version::$sso_service_version"
          echo "::set-output name=usuaris_web_version::$usuaris_web_version"

      - name: Execute SSH Command
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            echo "Deploying SSO SERVICE VERSION: ${{ steps.versions.outputs.sso_service_version }}"
            echo "Deploying USUARIS WEB VERSION: ${{ steps.versions.outputs.usuaris_web_version }}"
            cd ${{ secrets.SSO_PATH }}/dev
            bash deploy.sh sso ${{ steps.versions.outputs.sso_service_version }} ${{ steps.versions.outputs.usuaris_web_version }}
