name: deploy_front_dev

on:
  pull_request:
    branches:
      - main
    types:
      - closed
    paths:
      - "config/dev/front.yml"

jobs:
  deploy_front_dev:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Get versions
        id: versions
        run: |
          back_version=$(grep version: ./config/dev/back.yml | awk '{print $2}')
          front_version=$(grep version: ./config/dev/front.yml | awk '{print $2}')
          echo "::set-output name=back_version::$back_version"
          echo "::set-output name=front_version::$front_version"

      - name: Execute SSH Command
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            echo "Deploying Back Version: ${{ steps.versions.outputs.back_version }}"
            echo "Deploying Front Version: ${{ steps.versions.outputs.front_version }}"
            cd ${{ secrets.WIKI_PATH }}/dev
            bash deploy.sh front ${{ steps.versions.outputs.back_version }} ${{ steps.versions.outputs.front_version }}
