name: deploy_sso_dev

on:
  pull_request:
    branches:
      - main
    types:
      - closed
    paths:
      - "config/dev/sso.yml"

jobs:
  deploy_sso_dev:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Get versions
        id: versions
        run: |
          sso_version=$(grep version: ./config/dev/sso.yml | awk '{print $2}')
          echo "::set-output name=sso_version::$sso_version"

      - name: Execute SSH Command
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            echo "Deploying Back Version: ${{ steps.versions.outputs.sso_version }}"
            cd ${{ secrets.SSO_PATH }}/dev
            bash deploy.sh ${{ steps.versions.outputs.sso_version }}
