name: deploy_ui

on:
  pull_request:
    branches:
      - main
    types:
      - closed
    paths:
      - "config/prod/ui.yml"

jobs:
  deploy_ui:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Get versions
        id: versions
        run: |
          ui_version=$(grep version: ./config/prod/ui.yml | awk '{print $2}')
          echo "::set-output name=ui_version::$ui_version"

      - name: Execute SSH Command
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            echo "Deploying UI Version: ${{ steps.versions.outputs.ui_version }}"
            cd ${{ secrets.UI_PATH }}
            bash deploy.sh ${{ steps.versions.outputs.ui_version }}
