name: deploy_sso_front_dev

on:
  pull_request:
    branches:
      - main
    types:
      - closed
    paths:
      - "config/dev/sso_front.yml"

jobs:
  deploy_sso_front_dev:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Get versions
        id: versions
        run: |
          sso_version=$(grep version: ./config/dev/sso.yml | awk '{print $2}')
          sso_front_version=$(grep version: ./config/dev/sso_front.yml | awk '{print $2}')
          echo "::set-output name=sso_version::$sso_version"
          echo "::set-output name=sso_front_version::$sso_front_version"

      - name: Execute SSH Command
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            echo "Deploying SSO Version: ${{ steps.versions.outputs.sso_version }}"
            echo "Deploying SSO Front Version: ${{ steps.versions.outputs.sso_front_version }}"
            cd ${{ secrets.WIKI_PATH }}/dev
            bash deploy.sh sso_front ${{ steps.versions.outputs.sso_version }} ${{ steps.versions.outputs.sso_front_version }}
