name: e2e
on:
  schedule:
    - cron: "0 0 * * *" # daily at 12:00 AM
  
jobs:
  e2e:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: lts/*
    
    - name: Install dependencies
      run: |
        cd ${{ github.workspace }}/e2e
        npm ci

    - name: Install Playwright Browsers
      run: |
        cd ${{ github.workspace }}/e2e
        npx playwright install --with-deps

    - name: Run Playwright tests
      run: |
        cd ${{ github.workspace }}/e2e
        npx playwright test
    
    - uses: actions/upload-artifact@v4
      if: always()
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: 30
