name: Frontend on Pull Request

on:
  pull_request:
    branches:
      - main
    paths:
      - "front/**"

jobs:
  frontend:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"
          cache: "npm"
          cache-dependency-path: front/package-lock.json

      - name: install dependencies
        run: |
            cd ${{ github.workspace }}/front
            npm ci --legacy-peer-deps

      - name: lint
        run: |
            cd ${{ github.workspace }}/front
            npx eslint src --max-warnings 0

      - name: test
        run: |
            cd ${{ github.workspace }}/front
            npm run test -- --coverage

      - name: build
        run: |
            cd ${{ github.workspace }}/front
            npm run build
      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          projectBaseDir: front
          args: >
            -Dsonar.projectKey=busco-graphile-front
            -Dsonar.projectName="Frontend React App"
            -Dsonar.sources=src
            -Dsonar.exclusions=**/node_modules/**
            -Dsonar.tests=src
            -Dsonar.test.inclusions=**/*.test.ts,**/*.test.tsx
            -Dsonar.javascript.lcov.reportPaths=coverage/lcov.info
            -Dsonar.typescript.lcov.reportPaths=coverage/lcov.info