name: Build and Deploy

on:
  release:
    types: [published]
    tags:
      - front-v*.*.*

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
            node-version: 18
      
      - name: Install dependencies
        run: cd ./front && npm ci --legacy-peer-deps

      - name: lint
        run: cd ./front && npx eslint src --max-warnings 0

      - name: test
        run: cd ./front && npm run test

      - name: Build React TypeScript project
        run: cd ./front && npm run build
      
      - name: Deploy to server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            # Add your deployment commands here.
            # TO BE DONE WHEN READY FOR PROD
            